package nescpu

var cpu_ops = [256]CPU6502instr{
	// 0x0_
	{OpSize: 1, OpTime: 7, OpExtraTime: 0, OpFunc: opBrk, AddrFunc: addrImplied}, // BRK
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrIndX},    // ORA IND_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrZp},  // ORA ZP
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrZp}, // ASL ZP
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 3, OpExtraTime: 0, OpFunc: opPhp, AddrFunc: addrImplied},   // PHP
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrImmediate}, // ORA IMM
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opAsla, AddrFunc: addrAccum},    // ASLA
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbs},  // ORA ABS
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrAbs}, //ASL ABS
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x1_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBpl, AddrFunc: addrRelative}, //BPL
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrIndY},     // ORA IND_Y
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrZpX},  // ORA ZP_X
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrZpX}, // ASL ZP_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opClc, AddrFunc: addrImplied}, // CLC
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbsY},    // ORA ABS_Y
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbsX},  // ORA ABS_X
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrAbsX}, // ASL ABS_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x2_
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opJsr, AddrFunc: addrAbs},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opBit, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opRolm, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opPlp, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opRola, AddrFunc: addrAccum},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opBit, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opRolm, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x3_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBmi, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opRolm, AddrFunc: addrZpX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opSec, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAnd, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opRolm, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x4_
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opRti, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opLsrm, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 3, OpExtraTime: 0, OpFunc: opPha, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opLsra, AddrFunc: addrAccum},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 3, OpExtraTime: 0, OpFunc: opJmp, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opLsrm, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x5_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBvc, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opLsrm, AddrFunc: addrZpX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opCli, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opEor, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opLsrm, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x6_
	{OpSize: 1, OpTime: 6, OpExtraTime: 0, OpFunc: opRts, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opRorm, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opPla, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opRora, AddrFunc: addrAccum},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opJmp, AddrFunc: addrIndirect},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opRorm, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x7_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBvs, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opRorm, AddrFunc: addrZpX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opSei, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opAdc, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opRorm, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x8_
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opSty, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opStx, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opDey, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTxa, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opSty, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opStx, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x9_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBcc, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opSty, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opStx, AddrFunc: addrZpY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTya, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrAbsY},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTxs, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opSta, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xA_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opLdy, AddrFunc: addrImmediate},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrIndX},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opLdx, AddrFunc: addrImmediate},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opLdy, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opLdx, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTay, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTax, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLdy, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLdx, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xB_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBcs, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opLdy, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opLdx, AddrFunc: addrZpY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opClv, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrAbsY},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opTsx, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLdy, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLda, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opLdx, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xC_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opCpy, AddrFunc: addrImmediate},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opCpy, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opDec, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opIny, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opDex, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opCpy, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opDec, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xD_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBne, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opDec, AddrFunc: addrZpX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opCld, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opCmp, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opDec, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xE_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opCpx, AddrFunc: addrImmediate},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrIndX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opCpx, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrZp},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opInc, AddrFunc: addrZp},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opInx, AddrFunc: addrImplied},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrImmediate},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opNop, AddrFunc: addrImplied},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opCpx, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrAbs},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opInc, AddrFunc: addrAbs},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xF_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBeq, AddrFunc: addrRelative},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrIndY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrZpX},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opInc, AddrFunc: addrZpX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opSed, AddrFunc: addrImplied},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrAbsY},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opSbc, AddrFunc: addrAbsX},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opInc, AddrFunc: addrAbsX},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
}
