package nescpu

var cpu_ops = [256]CPU6502instr{
	// 0x0_
	{OpSize: 1, OpTime: 7, OpExtraTime: 0, OpFunc: opBrk, AddrFunc: addrImplied}, // BRK
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrIndX},    // ORA IND_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrZp},  // ORA ZP
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrZp}, // ASL ZP
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 3, OpExtraTime: 0, OpFunc: opPhp, AddrFunc: addrImplied},   // PHP
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrImmediate}, // ORA IMM
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opAsla, AddrFunc: addrAccum},    // ASLA
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbs},  // ORA ABS
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrAbs}, //ASL ABS
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x1_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opBpl, AddrFunc: addrRelative}, //BPL
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrIndY},     // ORA IND_Y
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrZpX},  // ORA ZP_X
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrZpX}, // ASL ZP_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opClc, AddrFunc: addrImplied}, // CLC
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbsY},    // ORA ABS_Y
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opOra, AddrFunc: addrAbsX},  // ORA ABS_X
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opAslm, AddrFunc: addrAbsX}, // ASL ABS_X
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x2_
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x3_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x4_
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x5_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x6_
	{OpSize: 1, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x7_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x8_
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0x9_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xA_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xB_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xC_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xD_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xE_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 3, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	// 0xF_
	{OpSize: 2, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 5, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 2, OpTime: 6, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 1, OpTime: 2, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 4, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 3, OpTime: 7, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
	{OpSize: 0, OpTime: 0, OpExtraTime: 0, OpFunc: opUnimpl, AddrFunc: addrUnimpl},
}
