package NesCpu
/* Take argument of operand (if any). Perform operations. Set CPU flags.
       void op_bpl(signed char);
       void op_brk();
       void op_ora(int);
       void op_aslm(int);
       void op_asla();
       void op_php();
       void op_clc();
       void op_jsr(int);
       void op_bit(int);
       void op_and(int);
       void op_rolm(int);
       void op_plp();
       void op_rola();
       void op_bmi(signed char);
       void op_sec();
       void op_rti();
       void op_eor(int);
       void op_lsrm(int);
       void op_pha();
       void op_lsra();
       void op_jmp(int);
       void op_bvc(signed char);
       void op_cli();
       void op_rts();
       void op_adc(int);
       void op_rorm(int);
       void op_pla();
       void op_rora();
       void op_bvs(signed char);
       void op_sei();
       void op_sty(int);
       void op_sta(int);
       void op_stx(int);
       void op_dey();
       void op_txa();
       void op_bcc(signed char);
       void op_tya();
       void op_txs();
       void op_ldy(int);
       void op_lda(int);
       void op_ldx(int);
       void op_tay();
       void op_tax();
       void op_bcs(signed char);
       void op_clv();
       void op_tsx();
       void op_cpy(int);
       void op_cmp(int);
       void op_dec(int);
       void op_iny();
       void op_dex();
       void op_bne(signed char);
       void op_cld();
       void op_cpx(int);
       void op_sbc(int);
       void op_inc(int);
       void op_inx();
       void op_nop();
       void op_beq(signed char);
       void op_sed();
*/
